# ORIGINAL: the dispatch manifest JET checks; no swipl-devel counterpart.
# test/static_analysis_manifest.jl — the concrete call signatures the JET/AllocCheck gate analyses.
#
# 🔴 EVERY method LogicKernel defines (its own functions AND its methods on Base functions) must be
# reached by an entry here, or `test_static_analysis.jl` FAILS and names the method. So a new
# function cannot land without being checked for runtime dispatch — that is the point.
#
# DISPATCH_MANIFEST: (function, Tuple{argument types...}, must_not_allocate::Bool)
#   CONCRETE argument types only — the gate analyses exactly these specialisations.
# DISPATCH_EXEMPT:   (function, Tuple{...}) => "reason"   — a method that legitimately cannot be
#   called with the reference types. An empty reason, or an entry naming no method of LogicKernel,
#   fails the gate.
#
# Three instantiations of the default term type, chosen to cover the three payload shapes:
#   one concrete type · a union of 3 (+ Nothing = 4, the compiler's union-splitting limit) · a container.
const _M1 = Term{Float64}
const _M2 = DefaultTerm
const _M3 = Term{Vector{Float64}}

const LK = LogicKernel

_manifest_per_type(T) = (
    # the term interface — field reads, must not allocate
    (kind, Tuple{T}, true), (nchildren, Tuple{T}, true), (child, Tuple{T, Int}, true),
    (sym_key, Tuple{T}, true), (var_key, Tuple{T}, true), (gnd_key, Tuple{T}, true),
    (is_ground, Tuple{T}, true),
    (is_ground_walk, Tuple{T}, false),
    (gnd_equal, Tuple{T, T}, false), (atomic_compare, Tuple{T, T}, false),
    (mk_var, Tuple{Type{T}, UInt64}, false),
    (mk_expr, Tuple{Type{T}, Vector{T}}, false),
    (sym_term, Tuple{Type{T}, Symbol}, false),
    # the standard order — the ported chain, every link
    (compareStandard, Tuple{T, T}, false), (compareStandard, Tuple{T, T, Bool}, false),
    (LK.compare_std, Tuple{T, T, Int}, false),
    (LK.compare_fast, Tuple{T, T, Int}, false),
    (LK.do_compare, Tuple{T, T, Int}, false),
    (LK.compare_primitives, Tuple{T, T, Int}, false),
    (LK.compare_functors, Tuple{T, T, Int}, false), (LK._atomic_rank, Tuple{T}, false),
    # Base methods on the default type
    (Base.:(==), Tuple{T, T}, false), (Base.hash, Tuple{T, UInt}, false),
    (Base.show, Tuple{IOBuffer, T}, false)
)

const DISPATCH_MANIFEST = (
    _manifest_per_type(_M1)...,
    _manifest_per_type(_M2)...,
    _manifest_per_type(_M3)...,
    # payload-specific entry points
    (gnd_term, Tuple{Type{_M1}, Float64}, false),
    (gnd_term, Tuple{Type{_M2}, Int64}, false), (gnd_term, Tuple{Type{_M2}, String}, false),
    (gnd_term, Tuple{Type{_M3}, Vector{Float64}}, false),
    (LK._gnd_eq, Tuple{Float64, _M1}, false), (LK._gnd_eq, Tuple{Int64, _M2}, false),
    (LK._gnd_eq, Tuple{Vector{Float64}, _M3}, false),
    (LK._compare_other, Tuple{Vector{Float64}, _M3}, false),
    (LK._compare_other, Tuple{Int64, _M2}, false),
    (gnd_value_key, Tuple{Float64}, false), (gnd_value_key, Tuple{Int64}, false),
    (gnd_value_key, Tuple{String}, false), (gnd_value_key, Tuple{Vector{Float64}}, false),
    # leaf comparisons and helpers
    (LK._sign, Tuple{Int}, true), (LK._tag_rank, Tuple{Kind}, true),
    (LK._sym_key, Tuple{Symbol}, true),
    (LK.compareAtoms, Tuple{Symbol, Symbol}, true),
    (LK.compareStrings, Tuple{String, String}, false),
    (LK._nan_value, Tuple{Float64}, true), (LK._nan_value, Tuple{BigFloat}, false),
    (LK.compare_neq_floats, Tuple{Float64, Float64}, true),
    (LK.compare_mixed_float_rational, Tuple{Float64, Int64}, true),
    (LK._is_number, Tuple{Float64}, true),
    (LK._cmp_types, Tuple{DataType, DataType}, false),
    (LK._compare_numbers, Tuple{Int64, Float64}, false),
    (LK._compare_numbers, Tuple{Float64, Float64}, false),
    (LK._compare_strings, Tuple{String, String}, false),
    # generated by `@enum Kind` (Julia 1.13) — found by the coverage gate, not by reading; checked
    # rather than exempted because checking it costs nothing
    (Base.Enums._enum_hash, Tuple{Kind, UInt64}, false)
)

# `is_ground(t)` with an untyped argument is the interface's FALLBACK for implementations without a
# cached bit; `Term` overrides it, so no reference type reaches it. (`Tuple{Int}` names the fallback
# method by a non-term argument type — it is the method `which` selects.) Its body is
# `is_ground_walk`, which IS in the manifest.
const DISPATCH_EXEMPT = (
    (
    (is_ground, Tuple{Int}) => "interface fallback; Term overrides it, and its body is_ground_walk is checked"
),
)
