# tools/port_check.jl — LogicKernel MIRRORS swipl-devel, and every file says where it came from.
#
# THE RULE (user, 2026-10-02: "match the structure of swipl-devel, function names as-is, so it is
# easy to compare and track incrementally"; then "full mirror", originals in the nearest SWI area):
#
#   * A PORT lives at upstream's own path, `.jl` for the extension:
#         swipl-devel  src/pl-prims.c            → src/pl-prims.jl
#         swipl-devel  boot/tabling.pl           → boot/tabling.jl
#         swipl-devel  tests/core_lang/x.pl      → test/core_lang/x.jl   (Julia requires `test/`)
#         scryer-prolog src/lib/tabling.pl       → scryer-prolog/src/lib/tabling.jl
#     swipl-devel is FIRST priority; scryer-prolog is the second reference.
#     It opens with   # UPSTREAM: <repo> <path> @ <commit>   (one or more; the FIRST fixes the path)
#                     # CLASS: code | design
#                     # COPYRIGHT: <the upstream copyright line, verbatim>   (required for code)
#   * A ported FUNCTION — or, in a test file, a ported test unit (`@testset "<name>"`) — keeps
#     upstream's name (`!` appended when it mutates an argument), preceded by
#         # PORT: <upstream-basename> <name> [as <julia-name>]
#     `as` is ONLY for names Julia cannot spell (a Prolog `$name`, a clash with Base). Where multiset
#     semantics force a different behaviour:  # DIVERGES: <reason>  (after the PORT line)
#   * Code with no upstream counterpart opens with  # ORIGINAL: <why>  and lives in the nearest SWI
#     area: `src/` for source, `test/<SWI tests area>/` for its tests, `test/` root for package
#     infrastructure — never at a path that shadows an upstream file, never in `boot/`.
#   * Directories exist only where swipl-devel has them: `src/<d>` for d in swipl-devel's src/
#     subdirectories, `test/<area>` for its tests/ areas.
#
# CHECKED — structure always; upstream EXISTENCE where a checkout is found (~/dev-zone/<repo>, or
# LOGICKERNEL_UPSTREAM_<REPO>); CI has none, so CI checks structure + inventory and every local
# suite run also checks existence:
#   header present and unambiguous · class · known repo · the file at its mirrored path · directories
#   that mirror swipl-devel (the snapshot below is itself verified against the checkout) · no PORT
#   marker in an ORIGINAL file · each PORT names one of the file's upstream files and is followed by
#   a definition / @testset of exactly that name (found by PARSING) · every DIVERGES has a reason ·
#   commit exists · upstream file exists at it · each PORT name occurs in it · each COPYRIGHT line
#   occurs in it · no ORIGINAL file shadows an upstream file · docs/port_inventory.md's generated
#   table equals the headers.
# Markers are read from COMMENT TOKENS (Base.JuliaSyntax), so `# PORT:` inside a string — this
# tool's own test fixtures — is never mistaken for one.
#
#   julia --project=. tools/port_check.jl                    # check, exit 0/1
#   julia --project=. tools/port_check.jl --write-inventory  # regenerate the inventory table
# The suite runs it (test/test_port_check.jl), with a fixture proving every check can fail.

# Priority order: swipl-devel first. `swipl-bench` is swipl-devel's `bench/` SUBMODULE
# (github.com/SWI-Prolog/bench) — its own repository and commits, mounted at bench/ as upstream does.
const PORT_REPOS = ("swipl-devel", "swipl-bench", "scryer-prolog")
const _DEFAULT_CHECKOUT = Dict("swipl-bench" => joinpath("swipl-devel", "bench"))
const SCAN_ROOTS = ("src", "boot", "test", "bench", "scryer-prolog")
# swipl-devel's directory structure at bae881a24a3f — what `src/`, `test/` and `bench/` may contain.
# Verified against a live checkout on every local run (SNAPSHOT-STALE), so it cannot drift silently.
const SWI_SRC_DIRS = ("Unicode", "compat", "config", "libbf", "libtai", "minizip", "os",
    "test",
    "tools", "wasm")
const SWI_BENCH_DIRS = ("port", "programs")
const SWI_TEST_AREAS = ("GC", "attvar", "charset", "clp", "compile", "core_lang",
    "core_text", "db",
    "debug", "eclipse", "engines", "files", "foreign", "library", "rational", "save",
    "signals",
    "tabling", "thread", "thread_wait", "transaction", "unprotected", "xsb")
const RX_UPSTREAM = r"^#\s*UPSTREAM:\s*(\S+)\s+(\S+)\s+@\s+([0-9a-f]{7,40})\s*$"
const RX_CLASS = r"^#\s*CLASS:\s*(\S*)\s*$"
const RX_COPYRIGHT = r"^#\s*COPYRIGHT:\s*(.*?)\s*$"
const RX_ORIGINAL = r"^#\s*ORIGINAL:\s*(.*?)\s*$"
const RX_PORT = r"^#\s*PORT:\s*(\S+)\s+(\S+)(?:\s+as\s+(\S+))?\s*$"
const RX_PORT_ANY = r"^#\s*PORT:"
const RX_DIVERGES = r"^#\s*DIVERGES:\s*(.*?)\s*$"
const INVENTORY_BEGIN = "<!-- BEGIN GENERATED by tools/port_check.jl --write-inventory — do not hand-edit -->"
const INVENTORY_END = "<!-- END GENERATED -->"

struct UpstreamRef
    repo::String
    path::String
    commit::String
end

struct PortMarker
    line::Int
    upstream_base::String
    name::String
    jl_name::String
    diverges::Bool
    diverges_reason::String
end

struct SourceFile
    rel::String                      # path relative to the package root
    upstreams::Vector{UpstreamRef}
    class::String
    copyright::Vector{String}
    original::Bool
    original_reason::String
    markers::Vector{PortMarker}
end

"Default checkout for an upstream repo: `LOGICKERNEL_UPSTREAM_<REPO>` or `~/dev-zone/<repo>`."
function default_upstream_dirs()::Dict{String, String}
    d = Dict{String, String}()
    for r in PORT_REPOS
        env = "LOGICKERNEL_UPSTREAM_" * uppercase(replace(r, "-" => "_"))
        d[r] = get(ENV, env, joinpath(homedir(), "dev-zone", get(_DEFAULT_CHECKOUT, r, r)))
    end
    return d
end

"The package-relative path a port of `repo`/`path` must live at."
function expected_path(repo::AbstractString, path::AbstractString)::String
    p = replace(String(path), r"\.[A-Za-z0-9]+$" => "") * ".jl"
    if repo == first(PORT_REPOS)
        return startswith(p, "tests/") ? "test/" * p[7:end] : p
    end
    repo == "swipl-bench" && return "bench/" * p           # mounted where swipl-devel mounts it
    return string(repo, "/", p)
end

"Upstream paths an ORIGINAL file at `rel` would shadow (swipl-devel)."
function shadowed_paths(rel::AbstractString)::Vector{String}
    stem = replace(String(rel), r"\.jl$" => "")
    startswith(stem, "test/") && return ["tests/" * stem[6:end] * ".pl"]
    return [stem * ext for ext in (".c", ".h", ".pl")]
end

# ── parsing: the definitions (and test units) a file makes, with their lines ─────────────────────
function _callname(x)::Union{String, Nothing}
    x isa Symbol && return String(x)
    x isa Expr || return nothing
    x.head in (:where, :(::)) && return _callname(x.args[1])
    if x.head === :call
        f = x.args[1]
        f isa Symbol && return String(f)
        if f isa Expr && f.head === :.
            q = f.args[end]
            return q isa QuoteNode ? String(q.value) : nothing
        end
        f isa Expr && f.head === :curly && return _callname(f.args[1])
    end
    return nothing
end

_is_def_lhs(x) =
    x isa Expr &&
    (x.head === :call || (x.head in (:where, :(::)) && _is_def_lhs(x.args[1])))
_is_testset(ex) = ex isa Expr && ex.head === :macrocall && ex.args[1] === Symbol("@testset")

function _defname(ex)::Union{String, Nothing}
    ex isa Expr || return nothing
    ex.head === :function && return _callname(ex.args[1])
    ex.head === :(=) && _is_def_lhs(ex.args[1]) && return _callname(ex.args[1])
    if _is_testset(ex)                                  # a test unit: its name is its first string
        i = findfirst(a -> a isa String, ex.args)
        return i === nothing ? nothing : ex.args[i]
    end
    if ex.head === :macrocall                           # @inline function …, docstring + definition
        for a in ex.args
            n = _defname(a)
            n === nothing || return n
        end
    end
    return nothing
end

function _collect_defs!(out::Vector{Tuple{Int, String}}, ex, line::Int)
    ex isa Expr || return out
    if ex.head in (:toplevel, :block)
        cur = line
        for a in ex.args
            a isa LineNumberNode ? (cur = a.line) : _collect_defs!(out, a, cur)
        end
        return out
    elseif ex.head === :module
        return _collect_defs!(out, ex.args[3], line)
    end
    n = _defname(ex)
    n === nothing || push!(out, (line, n))
    if _is_testset(ex) || (ex.head in (:for, :let, :if) || ex.head === :do)   # units nest
        for a in ex.args
            _collect_defs!(out, a, line)
        end
    end
    return out
end

"Function definitions and `@testset` units in `text`, as (line, name), in line order."
function definitions(
    text::AbstractString, filename::AbstractString
)::Vector{Tuple{Int, String}}
    defs = _collect_defs!(Tuple{Int, String}[], Meta.parseall(text; filename=filename), 0)
    return sort!(defs)
end

"Every COMMENT in `text`, as (line, stripped text) — strings and code are never mistaken for one."
function comment_lines(text::AbstractString)::Vector{Tuple{Int, String}}
    out = Tuple{Int, String}[]
    line, pos = 1, 1
    for t in Base.JuliaSyntax.tokenize(text)
        r = t.range
        Base.JuliaSyntax.kind(t) == Base.JuliaSyntax.K"Comment" || continue
        line += count(==(0x0a), codeunits(text)[pos:(first(r) - 1)])     # bytes, so 0x0a — not '\n'
        pos = first(r)
        push!(out, (line, strip(String(codeunits(text)[r]))))
    end
    return out
end

# ── reading one source file's provenance ─────────────────────────────────────────────────────────
function read_source(root::String, rel::String, violations::Vector{String})::SourceFile
    text = read(joinpath(root, rel), String)
    ups = UpstreamRef[]
    class = ""
    copyright = String[]
    original = false
    original_reason = ""
    for l in eachline(IOBuffer(text))                # the header: leading comments/blank lines
        s = strip(l)
        isempty(s) && continue
        startswith(s, "#") || break
        if (m = match(RX_UPSTREAM, s)) !== nothing
            push!(ups, UpstreamRef(m[1], m[2], m[3]))
        elseif occursin(r"^#\s*UPSTREAM:", s)
            push!(
                violations,
                "MARKER-MALFORMED $rel: `$s` (want `# UPSTREAM: <repo> <path> @ <commit>`)"
            )
        elseif (m = match(RX_CLASS, s)) !== nothing
            class = m[1]
        elseif (m = match(RX_COPYRIGHT, s)) !== nothing
            push!(copyright, m[1])
        elseif (m = match(RX_ORIGINAL, s)) !== nothing
            original = true
            original_reason = m[1]
        end
    end
    markers = PortMarker[]
    for (i, c) in comment_lines(text)
        if (m = match(RX_PORT, c)) !== nothing
            jl = m[3] === nothing ? m[2] : m[3]
            push!(markers, PortMarker(i, m[1], m[2], jl, false, ""))
        elseif occursin(RX_PORT_ANY, c)
            push!(
                violations,
                "MARKER-MALFORMED $rel:$i: `$c` (want `# PORT: <upstream-file> <name> [as <julia-name>]`)"
            )
        elseif (m = match(RX_DIVERGES, c)) !== nothing
            if isempty(markers)
                push!(violations, "DIVERGES-ORPHAN $rel:$i: no PORT marker above it")
            else
                p = markers[end]
                markers[end] = PortMarker(
                    p.line, p.upstream_base, p.name, p.jl_name, true, m[1]
                )
            end
        end
    end
    return SourceFile(rel, ups, class, copyright, original, original_reason, markers)
end

# ── upstream access (git, read-only) ─────────────────────────────────────────────────────────────
_git_ok(dir, args...) =
    success(pipeline(`git -C $dir $args`; stdout=devnull, stderr=devnull))
_git_show(dir, spec) = read(pipeline(`git -C $dir show $spec`; stderr=devnull), String)
"Directories of `path` at HEAD in the checkout `dir` (`path == \".\"` — its root)."
function _git_dirs(dir, path)::Vector{String}
    cmd = if path == "."
        `git -C $dir ls-tree -d --name-only HEAD`
    else
        `git -C $dir ls-tree -d --name-only HEAD $path/`
    end
    return sort!([
        basename(l) for l in eachline(IOBuffer(read(pipeline(cmd; stderr=devnull), String)))
    ])
end
_squash(s) = replace(strip(s), r"\s+" => " ")
_rx_escape(s) = replace(s, r"[\\^$.|?*+()\[\]{}]" => s"\\\0")
"`name` as a whole identifier (Prolog `\$name`s included) somewhere in `text`."
_word_in(name, text) =
    occursin(Regex("(?<![A-Za-z0-9_\$])" * _rx_escape(name) * "(?![A-Za-z0-9_])"), text)

# ── the inventory table ──────────────────────────────────────────────────────────────────────────
function inventory_table(files::Vector{SourceFile})::String
    rows = String[]
    for f in files, u in f.upstreams
        n = count(m -> m.upstream_base == basename(u.path), f.markers)     # markers naming THIS file
        push!(
            rows, "| $(u.repo) `$(u.path)` | $(f.class) | `$(u.commit)` | `$(f.rel)` | $n |"
        )
    end
    sort!(rows)
    head = "| upstream file | class | upstream commit | kernel file | ported units |\n|---|---|---|---|---|"
    return join([head; rows], "\n")
end

function _inventory_section(text::String)::Union{String, Nothing}
    i = findfirst(INVENTORY_BEGIN, text)
    j = findfirst(INVENTORY_END, text)
    (i === nothing || j === nothing || last(i) > first(j)) && return nothing
    return strip(text[(last(i) + 1):(first(j) - 1)])
end

function _scan_files(root::String)::Vector{String}
    rels = String[]
    for r in SCAN_ROOTS
        isdir(joinpath(root, r)) || continue
        for (d, _, fs) in walkdir(joinpath(root, r)), f in fs
            endswith(f, ".jl") && push!(rels, relpath(joinpath(d, f), root))
        end
    end
    return sort!(rels)
end

function _check_dirs!(v::Vector{String}, root::String)
    for (top, allowed) in
        (("src", SWI_SRC_DIRS), ("test", SWI_TEST_AREAS), ("bench", SWI_BENCH_DIRS))
        isdir(joinpath(root, top)) || continue
        for (d, ds, _) in walkdir(joinpath(root, top)), sub in ds
            rel = relpath(joinpath(d, sub), root)
            parts = splitpath(rel)
            length(parts) == 2 && !(parts[2] in allowed) &&
                push!(
                    v,
                    "DIR-NOT-UPSTREAM $rel: swipl-devel has no $(top == "test" ? "tests" : top)/$(parts[2])"
                )
        end
    end
    bootdir = joinpath(root, "boot")
    if isdir(bootdir)
        for (d, ds, _) in walkdir(bootdir), sub in ds
            push!(
                v,
                "DIR-NOT-UPSTREAM $(relpath(joinpath(d, sub), root)): swipl-devel's boot/ is flat"
            )
        end
    end
end

"""
    port_check(pkgroot; upstream_dirs = default_upstream_dirs(), inventory = "docs/port_inventory.md")
        -> (; violations, files, existence_checked)

`violations` are strings starting with a CODE (HEADER-MISSING, PATH-MISMATCH, DEF-MISMATCH, …) so a
test can assert exactly which checks fired. `existence_checked` lists the repos whose checkout was
found; ports into any other repo were checked for structure only.
"""
function port_check(pkgroot::AbstractString;
    upstream_dirs::Dict{String, String}=default_upstream_dirs(),
    inventory::AbstractString="docs/port_inventory.md")
    root = abspath(pkgroot)
    v = String[]
    files = [read_source(root, rel, v) for rel in _scan_files(root)]
    # `.git` is a FILE in a submodule checkout (swipl-devel/bench), a directory otherwise.
    available = Set(r for (r, d) in upstream_dirs if ispath(joinpath(d, ".git")))
    _check_dirs!(v, root)
    swi = first(PORT_REPOS)
    if swi in available
        live_src, live_tests = _git_dirs(upstream_dirs[swi], "src"),
        _git_dirs(upstream_dirs[swi], "tests")
        if !isempty(live_src) && (
            live_src != sort!(collect(SWI_SRC_DIRS)) ||
            live_tests != sort!(collect(SWI_TEST_AREAS))
        )
            push!(
                v,
                "SNAPSHOT-STALE tools/port_check.jl: SWI_SRC_DIRS/SWI_TEST_AREAS differ from $swi HEAD — update them"
            )
        end
    end
    # bench/ is a submodule: in swipl-devel it is a gitlink, so its directories come from the
    # submodule's own tree, not swipl-devel's.
    if "swipl-bench" in available
        live_bench = _git_dirs(upstream_dirs["swipl-bench"], ".")
        !isempty(live_bench) && live_bench != sort!(collect(SWI_BENCH_DIRS)) &&
            push!(
                v,
                "SNAPSHOT-STALE tools/port_check.jl: SWI_BENCH_DIRS differs from swipl-bench HEAD — update it"
            )
    end
    for f in files
        if f.original && !isempty(f.upstreams)
            push!(v, "HEADER-BOTH $(f.rel): both ORIGINAL and UPSTREAM")
        elseif !f.original && isempty(f.upstreams)
            push!(
                v,
                "HEADER-MISSING $(f.rel): needs `# UPSTREAM: …` or `# ORIGINAL: <why>` at the top"
            )
        end
        if f.original
            isempty(f.original_reason) && push!(v, "ORIGINAL-NO-REASON $(f.rel)")
            (startswith(f.rel, "boot/") || occursin(r"^src/pl-", f.rel)) &&
                push!(v, "ORIGINAL-PORT-NAME $(f.rel): that path is reserved for ports")
            isempty(f.markers) ||
                push!(
                    v, "ORIGINAL-HAS-PORT $(f.rel): a ported unit belongs in its port file"
                )
            if swi in available
                for p in shadowed_paths(f.rel)
                    _git_ok(upstream_dirs[swi], "cat-file", "-e", "HEAD:" * p) &&
                        push!(
                            v,
                            "ORIGINAL-SHADOWS-UPSTREAM $(f.rel): swipl-devel has $p — port it or rename"
                        )
                end
            end
            continue
        end
        isempty(f.upstreams) && continue
        f.class in ("code", "design") ||
            push!(v, "CLASS-MISSING $(f.rel): `# CLASS: code` or `design`")
        f.class == "code" && isempty(f.copyright) &&
            push!(
                v,
                "COPYRIGHT-ABSENT $(f.rel): a code port must carry the upstream copyright line(s)"
            )
        for u in f.upstreams
            u.repo in PORT_REPOS || push!(
                v,
                "UNKNOWN-REPO $(f.rel): `$(u.repo)` (known: $(join(PORT_REPOS, ", ")))"
            )
        end
        want = expected_path(f.upstreams[1].repo, f.upstreams[1].path)
        f.rel == want || push!(
            v,
            "PATH-MISMATCH $(f.rel): a port of $(f.upstreams[1].repo) $(f.upstreams[1].path) must live at $want"
        )
        defs = definitions(read(joinpath(root, f.rel), String), f.rel)
        bases = Set(basename(u.path) for u in f.upstreams)
        for (k, m) in enumerate(f.markers)
            m.upstream_base in bases ||
                push!(
                    v,
                    "MARKER-FILE-UNKNOWN $(f.rel):$(m.line): `$(m.upstream_base)` is not one of this file's UPSTREAM files"
                )
            m.diverges && isempty(m.diverges_reason) &&
                push!(v, "DIVERGES-NO-REASON $(f.rel):$(m.line)")
            nxt = findfirst(d -> d[1] > m.line, defs)
            stop = k < length(f.markers) ? f.markers[k + 1].line : typemax(Int)
            if nxt === nothing || defs[nxt][1] > stop
                push!(
                    v,
                    "MARKER-ORPHAN $(f.rel):$(m.line): no definition follows PORT $(m.name)"
                )
            elseif !(defs[nxt][2] == m.jl_name || defs[nxt][2] == m.jl_name * "!")
                push!(
                    v,
                    "DEF-MISMATCH $(f.rel):$(m.line): PORT $(m.name) is followed by `$(defs[nxt][2])`, want `$(m.jl_name)`"
                )
            end
        end
        for u in f.upstreams
            u.repo in available || continue
            dir = upstream_dirs[u.repo]
            if !_git_ok(dir, "cat-file", "-e", u.commit * "^{commit}")
                push!(v, "COMMIT-MISSING $(f.rel): $(u.repo) has no commit $(u.commit)")
                continue
            end
            if !_git_ok(dir, "cat-file", "-e", u.commit * ":" * u.path)
                push!(
                    v,
                    "UPSTREAM-FILE-MISSING $(f.rel): $(u.repo) $(u.path) does not exist at $(u.commit)"
                )
                continue
            end
            text = _git_show(dir, u.commit * ":" * u.path)
            if u === f.upstreams[1]
                sq = _squash(text)
                for c in f.copyright
                    occursin(_squash(c), sq) ||
                        push!(
                            v,
                            "COPYRIGHT-MISMATCH $(f.rel): `$c` is not in $(u.path) @ $(u.commit)"
                        )
                end
            end
            for m in f.markers
                m.upstream_base == basename(u.path) || continue
                _word_in(m.name, text) ||
                    push!(
                        v,
                        "UPSTREAM-NAME-MISSING $(f.rel):$(m.line): `$(m.name)` does not occur in $(u.path) @ $(u.commit)"
                    )
            end
        end
    end
    inv = joinpath(root, inventory)
    if !isfile(inv)
        push!(v, "INVENTORY-MISSING $inventory")
    else
        have = _inventory_section(read(inv, String))
        if have === nothing
            push!(
                v,
                "INVENTORY-MISSING $inventory: no generated section ($INVENTORY_BEGIN … $INVENTORY_END)"
            )
        elseif have != inventory_table(files)
            push!(
                v,
                "INVENTORY-DRIFT $inventory: differs from the headers — run tools/port_check.jl --write-inventory"
            )
        end
    end
    return (; violations=v, files=files, existence_checked=sort!(collect(available)))
end

"Rewrite the generated section of the inventory from the headers."
function write_inventory(
    pkgroot::AbstractString; inventory::AbstractString="docs/port_inventory.md"
)
    root = abspath(pkgroot)
    files = port_check(root).files
    inv = joinpath(root, inventory)
    text = read(inv, String)
    i = findfirst(INVENTORY_BEGIN, text)
    j = findfirst(INVENTORY_END, text)
    (i === nothing || j === nothing) && error("no generated section in $inventory")
    write(inv, text[1:last(i)] * "\n" * inventory_table(files) * "\n" * text[first(j):end])
    return inv
end

if abspath(PROGRAM_FILE) == @__FILE__
    root = joinpath(@__DIR__, "..")
    if "--write-inventory" in ARGS
        println("wrote ", write_inventory(root))
    end
    r = port_check(root)
    println("port_check: $(length(r.files)) file(s), upstream checked for: ",
        if isempty(r.existence_checked)
            "NONE (no checkout found)"
        else
            join(r.existence_checked, ", ")
        end)
    foreach(x -> println("  ", x), r.violations)
    exit(isempty(r.violations) && !isempty(r.files) ? 0 : 1)
end
