# tools/port_check.jl — LogicKernel MIRRORS swipl-devel, and every file says where it came from.
#
# THE RULE (user, 2026-10-02: "match the structure of swipl-devel, function names as-is, so it is
# easy to compare and track incrementally"; then "full mirror", originals in the nearest SWI area):
#
#   * A PORT lives at upstream's own path, `.jl` for the extension:
#         swipl-devel  src/pl-prims.c            → src/pl-prims.jl
#         swipl-devel  boot/tabling.pl           → boot/tabling.jl
#         swipl-devel  tests/core_lang/x.pl      → test/core_lang/x.jl   (Julia requires `test/`)
#         scryer-prolog src/lib/tabling.pl       → scryer-prolog/src/lib/tabling.jl
#     swipl-devel is FIRST priority; scryer-prolog is the second reference.
#     It opens with   # UPSTREAM: <repo> <path> @ <commit>   (one or more; the FIRST fixes the path)
#                     # CLASS: code | design
#                     # COPYRIGHT: <the upstream copyright line, verbatim>   (required for code)
#   * A ported FUNCTION — or, in a test file, a ported test unit (`@testset "<name>"`) — keeps
#     upstream's name (`!` appended when it mutates an argument), preceded by
#         # PORT: <upstream-basename> <name> [as <julia-name>]
#     `as` is ONLY for names Julia cannot spell (a Prolog `$name`, a clash with Base). Where multiset
#     semantics force a different behaviour:  # DIVERGES: <reason>  (after the PORT line)
#   * Code with no upstream counterpart opens with  # ORIGINAL: <why>  and lives in the nearest SWI
#     area: `src/` for source, `test/<SWI tests area>/` for its tests, `test/` root for package
#     infrastructure — never at a path that shadows an upstream file, never in `boot/`.
#   * Directories exist only where swipl-devel has them: `src/<d>` for d in swipl-devel's src/
#     subdirectories, `test/<area>` for its tests/ areas.
#
# CHECKED — structure always; upstream EXISTENCE where a checkout is found (~/dev-zone/<repo>, or
# LOGICKERNEL_UPSTREAM_<REPO>); CI has none, so CI checks structure + inventory and every local
# suite run also checks existence:
#   header present and unambiguous · class · known repo · the file at its mirrored path · directories
#   that mirror swipl-devel (the snapshot below is itself verified against the checkout) · no PORT
#   marker in an ORIGINAL file · each PORT names one of the file's upstream files and is followed by
#   a definition / @testset of exactly that name (found by PARSING) · every DIVERGES has a reason ·
#   commit exists · upstream file exists at it · each PORT name occurs in it · each COPYRIGHT line
#   occurs in it · no ORIGINAL file shadows an upstream file · docs/port_inventory.md's generated
#   table equals the headers · its VM inventory's `declared` column equals the `# PORT: pl-vmi.c`
#   markers.
# Markers are read from COMMENT TOKENS (Base.JuliaSyntax), so `# PORT:` inside a string — this
# tool's own test fixtures — is never mistaken for one.
#
#   julia --project=. tools/port_check.jl                    # check, exit 0/1
#   julia --project=. tools/port_check.jl --write-inventory  # regenerate the inventory table
# The suite runs it (test/test_port_check.jl), with a fixture proving every check can fail.

# Priority order: swipl-devel first. `swipl-bench` is swipl-devel's `bench/` SUBMODULE
# (github.com/SWI-Prolog/bench) — its own repository and commits, mounted at bench/ as upstream does.
const PORT_REPOS = ("swipl-devel", "swipl-bench", "scryer-prolog")
const _DEFAULT_CHECKOUT = Dict("swipl-bench" => joinpath("swipl-devel", "bench"))
const SCAN_ROOTS = ("src", "boot", "test", "bench", "scryer-prolog")
# swipl-devel's directory structure at bae881a24a3f — what `src/`, `test/` and `bench/` may contain.
# Verified against a live checkout on every local run (SNAPSHOT-STALE), so it cannot drift silently.
const SWI_SRC_DIRS = ("Unicode", "compat", "config", "libbf", "libtai", "minizip", "os",
    "test",
    "tools", "wasm")
const SWI_BENCH_DIRS = ("port", "programs")
const SWI_TEST_AREAS = ("GC", "attvar", "charset", "clp", "compile", "core_lang",
    "core_text", "db",
    "debug", "eclipse", "engines", "files", "foreign", "library", "rational", "save",
    "signals",
    "tabling", "thread", "thread_wait", "transaction", "unprotected", "xsb")
const RX_UPSTREAM = r"^#\s*UPSTREAM:\s*(\S+)\s+(\S+)\s+@\s+([0-9a-f]{7,40})\s*$"
const RX_CLASS = r"^#\s*CLASS:\s*(\S*)\s*$"
const RX_COPYRIGHT = r"^#\s*COPYRIGHT:\s*(.*?)\s*$"
const RX_ORIGINAL = r"^#\s*ORIGINAL:\s*(.*?)\s*$"
const RX_PORT = r"^#\s*PORT:\s*(\S+)\s+(\S+)(?:\s+as\s+(\S+))?\s*$"
const RX_PORT_ANY = r"^#\s*PORT:"
const RX_DIVERGES = r"^#\s*DIVERGES:\s*(.*?)\s*$"
const INVENTORY_BEGIN = "<!-- BEGIN GENERATED by tools/port_check.jl --write-inventory — do not hand-edit -->"
const INVENTORY_END = "<!-- END GENERATED -->"
const VM_INVENTORY_BEGIN = "<!-- BEGIN GENERATED VM inventory"
const VM_INVENTORY_END = "<!-- END GENERATED VM inventory -->"

struct UpstreamRef
    repo::String
    path::String
    commit::String
end

struct PortMarker
    line::Int
    upstream_base::String
    name::String
    jl_name::String
    diverges::Bool
    diverges_reason::String
end

struct SourceFile
    rel::String                      # path relative to the package root
    upstreams::Vector{UpstreamRef}
    class::String
    copyright::Vector{String}
    original::Bool
    original_reason::String
    markers::Vector{PortMarker}
end

"Default checkout for an upstream repo: `LOGICKERNEL_UPSTREAM_<REPO>` or `~/dev-zone/<repo>`."
function default_upstream_dirs()::Dict{String, String}
    d = Dict{String, String}()
    for r in PORT_REPOS
        env = "LOGICKERNEL_UPSTREAM_" * uppercase(replace(r, "-" => "_"))
        d[r] = get(ENV, env, joinpath(homedir(), "dev-zone", get(_DEFAULT_CHECKOUT, r, r)))
    end
    return d
end

"The package-relative path a port of `repo`/`path` must live at."
function expected_path(repo::AbstractString, path::AbstractString)::String
    p = replace(String(path), r"\.[A-Za-z0-9]+$" => "") * ".jl"
    if repo == first(PORT_REPOS)
        return startswith(p, "tests/") ? "test/" * p[7:end] : p
    end
    repo == "swipl-bench" && return "bench/" * p           # mounted where swipl-devel mounts it
    return string(repo, "/", p)
end

"Upstream paths an ORIGINAL file at `rel` would shadow (swipl-devel)."
function shadowed_paths(rel::AbstractString)::Vector{String}
    stem = replace(String(rel), r"\.jl$" => "")
    startswith(stem, "test/") && return ["tests/" * stem[6:end] * ".pl"]
    return [stem * ext for ext in (".c", ".h", ".pl")]
end

# ── parsing: the definitions (and test units) a file makes, with their lines ─────────────────────
function _callname(x)::Union{String, Nothing}
    x isa Symbol && return String(x)
    x isa Expr || return nothing
    x.head in (:where, :(::)) && return _callname(x.args[1])
    if x.head === :call
        f = x.args[1]
        f isa Symbol && return String(f)
        if f isa Expr && f.head === :.
            q = f.args[end]
            return q isa QuoteNode ? String(q.value) : nothing
        end
        f isa Expr && f.head === :curly && return _callname(f.args[1])
    end
    return nothing
end

_is_def_lhs(x) =
    x isa Expr &&
    (x.head === :call || (x.head in (:where, :(::)) && _is_def_lhs(x.args[1])))
_is_testset(ex) = ex isa Expr && ex.head === :macrocall && ex.args[1] === Symbol("@testset")

"""
The name a `struct` / `const` / `@enum` defines: `S`, `S{T}`, `S{T} <: A`, `const X = …`,
`const X{T} = …`, `@enum E::UInt8 …`.
"""
function _typename(x)::Union{String, Nothing}
    x isa Symbol && return String(x)
    x isa Expr || return nothing
    x.head in (:curly, :<:, :(=), :(::)) && return _typename(x.args[1])
    return nothing
end

function _defname(ex)::Union{String, Nothing}
    ex isa Expr || return nothing
    ex.head === :function && return _callname(ex.args[1])
    ex.head === :macro && return _callname(ex.args[1])   # a ported C macro (`one_cycle`)
    ex.head === :(=) && _is_def_lhs(ex.args[1]) && return _callname(ex.args[1])
    # a ported struct or constant (`clause_index`, `MIN_SPEEDUP`) is a definition too
    ex.head === :struct && return _typename(ex.args[2])
    ex.head === :const && return _typename(ex.args[1])
    if ex.head === :macrocall && ex.args[1] === Symbol("@enum")    # a ported C enum (`hash_algo`)
        i = findfirst(a -> !(a isa LineNumberNode), ex.args[2:end])
        return i === nothing ? nothing : _typename(ex.args[i + 1])
    end
    if _is_testset(ex)                                  # a test unit: its name is its first string
        i = findfirst(a -> a isa String, ex.args)
        return i === nothing ? nothing : ex.args[i]
    end
    if ex.head === :macrocall                           # @inline function …, docstring + definition
        for a in ex.args
            n = _defname(a)
            n === nothing || return n
        end
    end
    return nothing
end

# A `@label NAME` inside a function is a definition too: the VM's run loop holds the bodies of
# pl-vmi.c's instructions and helpers as labels, as upstream compiles pl-vmi.c into PL_next_solution.
function _collect_labels!(out::Vector{Tuple{Int, String}}, ex, line::Int)
    ex isa Expr || return out
    if ex.head === :macrocall && ex.args[1] === Symbol("@label")
        i = findfirst(a -> a isa Symbol, ex.args[2:end])
        i === nothing || push!(out, (line, String(ex.args[i + 1])))
        return out
    end
    cur = line
    for a in ex.args
        a isa LineNumberNode ? (cur = a.line) : _collect_labels!(out, a, cur)
    end
    return out
end

function _collect_defs!(out::Vector{Tuple{Int, String}}, ex, line::Int)
    ex isa Expr || return out
    if ex.head in (:toplevel, :block)
        cur = line
        for a in ex.args
            a isa LineNumberNode ? (cur = a.line) : _collect_defs!(out, a, cur)
        end
        return out
    elseif ex.head === :module
        return _collect_defs!(out, ex.args[3], line)
    end
    n = _defname(ex)
    n === nothing || push!(out, (line, n))
    # the labels of a function's body (through a docstring or `@inline`; a test unit's nested
    # functions are reached through its own recursion below)
    n === nothing || _is_testset(ex) || _collect_labels!(out, ex, line)
    if _is_testset(ex) || (ex.head in (:for, :let, :if) || ex.head === :do)   # units nest
        for a in ex.args
            _collect_defs!(out, a, line)
        end
    end
    return out
end

"Function definitions and `@testset` units in `text`, as (line, name), in line order."
function definitions(
    text::AbstractString, filename::AbstractString
)::Vector{Tuple{Int, String}}
    defs = _collect_defs!(Tuple{Int, String}[], Meta.parseall(text; filename=filename), 0)
    return sort!(defs)
end

"Every COMMENT in `text`, as (line, stripped text) — strings and code are never mistaken for one."
function comment_lines(text::AbstractString)::Vector{Tuple{Int, String}}
    out = Tuple{Int, String}[]
    line, pos = 1, 1
    for t in Base.JuliaSyntax.tokenize(text)
        r = t.range
        Base.JuliaSyntax.kind(t) == Base.JuliaSyntax.K"Comment" || continue
        line += count(==(0x0a), codeunits(text)[pos:(first(r) - 1)])     # bytes, so 0x0a — not '\n'
        pos = first(r)
        push!(out, (line, strip(String(codeunits(text)[r]))))
    end
    return out
end

# ── reading one source file's provenance ─────────────────────────────────────────────────────────
function read_source(root::String, rel::String, violations::Vector{String})::SourceFile
    text = read(joinpath(root, rel), String)
    ups = UpstreamRef[]
    class = ""
    copyright = String[]
    original = false
    original_reason = ""
    for l in eachline(IOBuffer(text))                # the header: leading comments/blank lines
        s = strip(l)
        isempty(s) && continue
        startswith(s, "#") || break
        if (m = match(RX_UPSTREAM, s)) !== nothing
            push!(ups, UpstreamRef(m[1], m[2], m[3]))
        elseif occursin(r"^#\s*UPSTREAM:", s)
            push!(
                violations,
                "MARKER-MALFORMED $rel: `$s` (want `# UPSTREAM: <repo> <path> @ <commit>`)"
            )
        elseif (m = match(RX_CLASS, s)) !== nothing
            class = m[1]
        elseif (m = match(RX_COPYRIGHT, s)) !== nothing
            push!(copyright, m[1])
        elseif (m = match(RX_ORIGINAL, s)) !== nothing
            original = true
            original_reason = m[1]
        end
    end
    markers = PortMarker[]
    for (i, c) in comment_lines(text)
        if (m = match(RX_PORT, c)) !== nothing
            jl = m[3] === nothing ? m[2] : m[3]
            push!(markers, PortMarker(i, m[1], m[2], jl, false, ""))
        elseif occursin(RX_PORT_ANY, c)
            push!(
                violations,
                "MARKER-MALFORMED $rel:$i: `$c` (want `# PORT: <upstream-file> <name> [as <julia-name>]`)"
            )
        elseif (m = match(RX_DIVERGES, c)) !== nothing
            if isempty(markers)
                push!(violations, "DIVERGES-ORPHAN $rel:$i: no PORT marker above it")
            else
                p = markers[end]
                markers[end] = PortMarker(
                    p.line, p.upstream_base, p.name, p.jl_name, true, m[1]
                )
            end
        end
    end
    return SourceFile(rel, ups, class, copyright, original, original_reason, markers)
end

# ── upstream access (git, read-only) ─────────────────────────────────────────────────────────────
_git_ok(dir, args...) =
    success(pipeline(`git -C $dir $args`; stdout=devnull, stderr=devnull))
_git_show(dir, spec) = read(pipeline(`git -C $dir show $spec`; stderr=devnull), String)
"Directories of `path` at HEAD in the checkout `dir` (`path == \".\"` — its root)."
function _git_dirs(dir, path)::Vector{String}
    cmd = if path == "."
        `git -C $dir ls-tree -d --name-only HEAD`
    else
        `git -C $dir ls-tree -d --name-only HEAD $path/`
    end
    return sort!([
        basename(l) for l in eachline(IOBuffer(read(pipeline(cmd; stderr=devnull), String)))
    ])
end
_squash(s) = replace(strip(s), r"\s+" => " ")
_rx_escape(s) = replace(s, r"[\\^$.|?*+()\[\]{}]" => s"\\\0")
"`name` as a whole identifier (Prolog `\$name`s included) somewhere in `text`."
_word_in(name, text) =
    occursin(Regex("(?<![A-Za-z0-9_\$])" * _rx_escape(name) * "(?![A-Za-z0-9_])"), text)

# ── the inventory table ──────────────────────────────────────────────────────────────────────────
function inventory_table(files::Vector{SourceFile})::String
    rows = String[]
    for f in files, u in f.upstreams
        mine = filter(m -> m.upstream_base == basename(u.path), f.markers)  # markers naming THIS file
        n, k = length(mine), count(m -> m.diverges, mine)
        push!(
            rows,
            "| $(u.repo) `$(u.path)` | $(f.class) | `$(u.commit)` | `$(f.rel)` | $n | $k |"
        )
    end
    sort!(rows)
    head = "| upstream file | class | upstream commit | kernel file | ported units | diverging |\n|---|---|---|---|---|---|"
    return join([head; rows], "\n")
end

function _inventory_section(text::String)::Union{String, Nothing}
    i = findfirst(INVENTORY_BEGIN, text)
    j = findfirst(INVENTORY_END, text)
    (i === nothing || j === nothing || last(i) > first(j)) && return nothing
    return strip(text[(last(i) + 1):(first(j) - 1)])
end

# The VM inventory's rows (`| `NAME` | line | operands | needed by | kernel |`) and the names whose
# `kernel` column says `declared`; `nothing` when the section is absent.
function _vm_inventory(
    text::String
)::Union{Nothing, @NamedTuple{rows::Int, declared::Set{String}, names::Set{String}}}
    i = findfirst(VM_INVENTORY_BEGIN, text)
    j = findfirst(VM_INVENTORY_END, text)
    (i === nothing || j === nothing || last(i) > first(j)) && return nothing
    rows, declared, names = 0, Set{String}(), Set{String}()
    for m in eachmatch(
        r"^\| `(\w+)` \| \d+ \|[^|]*\|[^|]*\|\s*(\S*)\s*\|$"m, text[last(i):first(j)]
    )
        rows += 1
        push!(names, m[1])
        m[2] == "declared" && push!(declared, m[1])
    end
    return (; rows, declared, names)
end

# The `kernel` column of the VM inventory is hand-kept; it went stale once (V1 L1 declared eight
# instructions and left their rows blank). It must name exactly the `# PORT: pl-vmi.c` markers of
# its rows — the `VMI()` instructions; pl-vmi.c's helpers and macros (`h_const`, `exit_continue`,
# `TRUST_CLAUSE`, …: labels in the run loop since V4a) are no rows of it.
function vm_inventory_violations(
    text::String, ported::Set{String}, inventory::String
)::Vector{String}
    vm = _vm_inventory(text)
    if vm === nothing
        isempty(ported) && return String[]
        return [
            "VM-INVENTORY-MISSING $inventory: $(length(ported)) pl-vmi.c port(s), no VM inventory section"
        ]
    end
    vm.rows == 0 && return [
        "VM-INVENTORY-MISSING $inventory: a VM inventory section with no instruction rows"
    ]
    ported = intersect(ported, vm.names)
    vm.declared == ported && return String[]
    unmarked = join(sort!(collect(setdiff(ported, vm.declared))), ", ")
    stale = join(sort!(collect(setdiff(vm.declared, ported))), ", ")
    return [
        "VM-INVENTORY-DRIFT $inventory: `declared` column ≠ `# PORT: pl-vmi.c` markers — ported, not declared: [$unmarked]; declared, not ported: [$stale]"
    ]
end

function _scan_files(root::String)::Vector{String}
    rels = String[]
    for r in SCAN_ROOTS
        isdir(joinpath(root, r)) || continue
        for (d, _, fs) in walkdir(joinpath(root, r)), f in fs
            endswith(f, ".jl") && push!(rels, relpath(joinpath(d, f), root))
        end
    end
    return sort!(rels)
end

function _check_dirs!(v::Vector{String}, root::String)
    for (top, allowed) in
        (("src", SWI_SRC_DIRS), ("test", SWI_TEST_AREAS), ("bench", SWI_BENCH_DIRS))
        isdir(joinpath(root, top)) || continue
        for (d, ds, _) in walkdir(joinpath(root, top)), sub in ds
            rel = relpath(joinpath(d, sub), root)
            parts = splitpath(rel)
            length(parts) == 2 && !(parts[2] in allowed) &&
                push!(
                    v,
                    "DIR-NOT-UPSTREAM $rel: swipl-devel has no $(top == "test" ? "tests" : top)/$(parts[2])"
                )
        end
    end
    bootdir = joinpath(root, "boot")
    if isdir(bootdir)
        for (d, ds, _) in walkdir(bootdir), sub in ds
            push!(
                v,
                "DIR-NOT-UPSTREAM $(relpath(joinpath(d, sub), root)): swipl-devel's boot/ is flat"
            )
        end
    end
end

# ── M1: LogicKernel's own code map, GENERATED (port_inventory.md row M1) ─────────────────────────
# `--write-inventory` writes three generated blocks and `port_check` holds each to its generator:
#   * the inventory table (above), now with a `diverging` column — from the headers and markers,
#     checked everywhere, CI included;
#   * COVERAGE (docs/port_inventory.md): per upstream file AT ITS RECORDED COMMIT, how many of its
#     functions carry a `# PORT:` marker, of how many, and how many of those diverge. Counting
#     upstream's functions needs the checkout, so this block is recomputed and compared only where
#     every checkout it names is found (as upstream existence is); without one it must still be
#     present and non-empty. Upstream drift (commits since) is NOT a block — it moves whenever the
#     checkout is pulled — and stays tools/upstream_drift.jl's report;
#   * the CODE GRAPH (docs/architecture.md): src/ in include order, an edge where a file uses a name
#     another file defines — checked everywhere.
# And the hand-kept "What is here now" table (docs/architecture.md, it drifted on 2026-10-03) is
# CHECKED: every src/ and bench/ file listed, every listed file present, each row's upstream column
# naming exactly its files' UPSTREAM headers. Every block goes through ONE extractor (`_section`)
# on both sides, and both sides must be non-empty.
const COVERAGE_BEGIN = "<!-- BEGIN GENERATED coverage by tools/port_check.jl --write-inventory — do not hand-edit -->"
const COVERAGE_END = "<!-- END GENERATED coverage -->"
const GRAPH_BEGIN = "<!-- BEGIN GENERATED code graph by tools/port_check.jl --write-inventory — do not hand-edit -->"
const GRAPH_END = "<!-- END GENERATED code graph -->"
const WHATS_HERE_HEADING = "## What is here now"

# ⚠️ The upstream function list is a HEURISTIC, by language: C — an identifier at column 0
# followed by `(` on a line not ending in `;` (SWI's style puts the return type on the line above),
# plus `PRED_IMPL("name", …)` and pl-vmi.c's `VMI(NAME, …)` instructions; Prolog — clause heads at column 0; Rust — `fn name`. Good enough to
# rank what is left; never a reason to claim something "is not upstream" — the exact word search
# above is the authority for that.
"Function/predicate names defined in an upstream source text (heuristic, see the header)."
function upstream_names(path::AbstractString, text::AbstractString)::Vector{String}
    names = String[]
    if occursin(r"\.(c|h)$", path)
        for l in eachline(IOBuffer(text))
            m = match(r"^([A-Za-z_]\w*)\s*\(", l)
            m !== nothing && !endswith(rstrip(l), ";") && !startswith(l, "PRED_IMPL") &&
                !startswith(l, "VMI(") && push!(names, m[1])
            m = match(r"^VMI\((\w+)\s*,", l)                   # pl-vmi.c: an instruction
            m === nothing || push!(names, m[1])
            m = match(r"^PRED_IMPL\(\"([^\"]+)\"", l)
            m === nothing || push!(names, m[1])
        end
    elseif endswith(path, ".pl")
        for l in eachline(IOBuffer(text))
            m = match(r"^'?(\$?[a-z][A-Za-z0-9_]*)'?\s*(\(|:-|-->|\.)", l)
            m === nothing || push!(names, m[1])
        end
    elseif endswith(path, ".rs")
        for m in eachmatch(r"\bfn\s+([A-Za-z_]\w*)", text)
            push!(names, m[1])
        end
    end
    return sort!(unique!(names))
end

"The content between `b` and `e` in `text`, stripped; `nothing` when either is missing or misordered."
function _section(text::AbstractString, b::AbstractString, e::AbstractString)
    i = findfirst(b, text)
    j = findfirst(e, text)
    (i === nothing || j === nothing || last(i) > first(j)) && return nothing
    return String(strip(text[(last(i) + 1):(first(j) - 1)]))
end

"`gen` as `write_inventory` writes it between `b` and `e` — read back through `_section`."
_wrapped(gen::AbstractString, b, e) = _section(string(b, "\n", gen, "\n", e), b, e)

"""
The coverage table: one row per upstream file (repo, path, recorded commit) — its functions with a
`# PORT:` marker in any kernel file, of how many (`upstream_names` at that commit), how many of
those diverge — and a total. `nothing` when a checkout it needs is missing.
"""
function coverage_table(
    files::Vector{SourceFile}, upstream_dirs::Dict{String, String}
)::Union{Nothing, String}
    groups = Dict{Tuple{String, String, String}, Vector{SourceFile}}()
    for f in files, u in f.upstreams
        push!(get!(groups, (u.repo, u.path, u.commit), SourceFile[]), f)
    end
    rows = String[]
    tn, tm, tk = 0, 0, 0
    for key in sort!(collect(keys(groups)))
        repo, path, commit = key
        dir = get(upstream_dirs, repo, "")
        ispath(joinpath(dir, ".git")) || return nothing
        _git_ok(dir, "cat-file", "-e", commit * ":" * path) || return nothing
        un = Set(upstream_names(path, _git_show(dir, commit * ":" * path)))
        ported = Dict{String, Bool}()                     # function => some marker diverges
        for f in groups[key], m in f.markers
            (m.upstream_base == basename(path) && m.name in un) || continue
            ported[m.name] = get(ported, m.name, false) || m.diverges
        end
        n, m, k = length(ported), length(un), count(values(ported))
        kfiles = join(sort!(unique!([f.rel for f in groups[key]])), ", ")
        push!(rows, "| $repo `$path` | `$commit` | $n | $m | $k | $kfiles |")
        tn, tm, tk = tn + n, tm + m, tk + k
    end
    isempty(rows) && return ""
    head = "| upstream file | upstream commit | functions ported | of | diverging | kernel file(s) |\n|---|---|---|---|---|---|"
    return join([head; rows; "| **total** | | **$tn** | **$tm** | **$tk** | |"], "\n")
end

"The files `src/LogicKernel.jl` includes, in order."
_include_order(root::AbstractString)::Vector{String} =
    if isfile(joinpath(root, "src", "LogicKernel.jl"))
        [
            String(m[1]) for m in eachmatch(
                r"^include\(\"([^\"]+)\"\)"m,
                read(joinpath(root, "src", "LogicKernel.jl"), String)
            )
        ]
    else
        String[]
    end

"Every identifier token of `text` (code only: comments and strings are other tokens)."
function _identifiers(text::AbstractString)::Set{String}
    out = Set{String}()
    for t in Base.JuliaSyntax.tokenize(text)
        Base.JuliaSyntax.kind(t) == Base.JuliaSyntax.K"Identifier" || continue
        push!(out, String(codeunits(text)[t.range]))
    end
    return out
end

"""
The code graph of src/ as mermaid: the included files in include order, and an edge `a --> b`
wherever `a` uses (as an identifier) a name `b` defines at top level. `""` when nothing is included.
"""
function code_graph(root::AbstractString)::String
    order = _include_order(root)
    isempty(order) && return ""
    texts = Dict(f => read(joinpath(root, "src", f), String) for f in order)
    definers = Dict{String, Set{Int}}()
    for (i, f) in enumerate(order), (_, name) in definitions(texts[f], f)
        push!(get!(definers, name, Set{Int}()), i)
    end
    id(f) = replace(replace(f, r"\.jl$" => ""), r"[^A-Za-z0-9]" => "_")
    lines = ["```mermaid", "graph LR"]
    foreach(f -> push!(lines, "    $(id(f))[\"$f\"]"), order)
    edges = Set{Tuple{Int, Int}}()
    for (i, f) in enumerate(order), name in _identifiers(texts[f]),
        j in get(definers, name, Set{Int}())

        j == i || push!(edges, (i, j))
    end
    for (i, j) in sort!(collect(edges))
        push!(lines, "    $(id(order[i])) --> $(id(order[j]))")
    end
    push!(lines, "```")
    return join(lines, "\n")
end

"Backticked spans of `cell`, with one `{a,b,…}` group expanded."
function _cell_paths(cell::AbstractString)::Vector{String}
    out = String[]
    for m in eachmatch(r"`([^`]+)`", cell)
        p = String(m[1])
        b = match(r"^(.*)\{([^}]*)\}(.*)$", p)
        if b === nothing
            push!(out, p)
        else
            append!(out, [string(b[1], x, b[3]) for x in split(b[2], ",")])
        end
    end
    return out
end

_glob_match(pat::AbstractString, s::AbstractString) =
    occursin(Regex("^" * replace(_rx_escape(pat), "\\*" => "[^/]*") * "\$"), s)

"""
The hand-kept "What is here now" table of `arch` held to the headers: WHATS-HERE-EMPTY,
-MISSING (a src/ or bench/ file not listed), -UNKNOWN (a listed file that does not exist),
-UPSTREAM (a row's upstream column ≠ its files' UPSTREAM headers).
"""
function whats_here_violations(
    root::String, files::Vector{SourceFile}, arch::AbstractString
)::Vector{String}
    v = String[]
    text = read(joinpath(root, arch), String)
    i = findfirst("\n" * WHATS_HERE_HEADING * "\n", text)
    i === nothing && return ["WHATS-HERE-EMPTY $arch: no `$WHATS_HERE_HEADING` section"]
    rest = text[(last(i) + 1):end]
    j = findfirst(r"\n## ", rest)
    sec = j === nothing ? rest : rest[1:first(j)]
    byrel = Dict(f.rel => f for f in files)
    listed = Set{String}()
    nrows = 0
    for l in eachline(IOBuffer(sec))
        startswith(l, "| `") || continue
        nrows += 1
        a = findfirst(" | ", l)
        z = findlast(" | ", l)
        (a === nothing || z === nothing) && continue
        paths = _cell_paths(l[3:(first(a) - 1)])
        ups = String[]
        for p in paths
            push!(listed, p)
            f = get(byrel, p, nothing)
            f === nothing && !isfile(joinpath(root, p)) &&
                push!(v, "WHATS-HERE-UNKNOWN $arch: `$p` is listed but does not exist")
            f === nothing || append!(ups, [u.path for u in f.upstreams])
        end
        toks = filter(t -> occursin('/', t), _cell_paths(l[(last(z) + 1):end]))
        ok =
            all(u -> any(t -> _glob_match(t, u), toks), ups) &&
            all(t -> any(u -> _glob_match(t, u), ups), toks)
        ok || push!(
            v,
            "WHATS-HERE-UPSTREAM $arch: the row of $(join(paths, ", ")) names [$(join(toks, ", "))], the headers [$(join(unique(ups), ", "))]"
        )
    end
    nrows == 0 && push!(v, "WHATS-HERE-EMPTY $arch: no rows in `$WHATS_HERE_HEADING`")
    for f in files
        (startswith(f.rel, "src/") || startswith(f.rel, "bench/")) && !(f.rel in listed) &&
            push!(v, "WHATS-HERE-MISSING $arch: `$(f.rel)` is not listed")
    end
    return v
end

"A generated block of `doc` against its generator's output — DRIFT, or EMPTY on either side."
function _block_violations(
    code::String, doc::AbstractString, text::AbstractString, gen::AbstractString, b, e
)::Vector{String}
    have = _section(text, b, e)
    want = _wrapped(gen, b, e)
    have === nothing && return ["$code-MISSING $doc: no generated section ($b … $e)"]
    isempty(want) &&
        return ["$code-EMPTY generator: it produced nothing to check $doc against"]
    isempty(have) && return ["$code-EMPTY $doc: the generated section is empty"]
    have == want && return String[]
    return [
        "$code-DRIFT $doc: differs from its generator — run tools/port_check.jl --write-inventory"
    ]
end

"""
    port_check(pkgroot; upstream_dirs = default_upstream_dirs(), inventory = "docs/port_inventory.md")
        -> (; violations, files, existence_checked)

`violations` are strings starting with a CODE (HEADER-MISSING, PATH-MISMATCH, DEF-MISMATCH, …) so a
test can assert exactly which checks fired. `existence_checked` lists the repos whose checkout was
found; ports into any other repo were checked for structure only.
"""
function port_check(pkgroot::AbstractString;
    upstream_dirs::Dict{String, String}=default_upstream_dirs(),
    inventory::AbstractString="docs/port_inventory.md",
    architecture::AbstractString="docs/architecture.md")
    root = abspath(pkgroot)
    v = String[]
    files = [read_source(root, rel, v) for rel in _scan_files(root)]
    # `.git` is a FILE in a submodule checkout (swipl-devel/bench), a directory otherwise.
    available = Set(r for (r, d) in upstream_dirs if ispath(joinpath(d, ".git")))
    _check_dirs!(v, root)
    swi = first(PORT_REPOS)
    if swi in available
        live_src, live_tests = _git_dirs(upstream_dirs[swi], "src"),
        _git_dirs(upstream_dirs[swi], "tests")
        if !isempty(live_src) && (
            live_src != sort!(collect(SWI_SRC_DIRS)) ||
            live_tests != sort!(collect(SWI_TEST_AREAS))
        )
            push!(
                v,
                "SNAPSHOT-STALE tools/port_check.jl: SWI_SRC_DIRS/SWI_TEST_AREAS differ from $swi HEAD — update them"
            )
        end
    end
    # bench/ is a submodule: in swipl-devel it is a gitlink, so its directories come from the
    # submodule's own tree, not swipl-devel's.
    if "swipl-bench" in available
        live_bench = _git_dirs(upstream_dirs["swipl-bench"], ".")
        !isempty(live_bench) && live_bench != sort!(collect(SWI_BENCH_DIRS)) &&
            push!(
                v,
                "SNAPSHOT-STALE tools/port_check.jl: SWI_BENCH_DIRS differs from swipl-bench HEAD — update it"
            )
    end
    for f in files
        if f.original && !isempty(f.upstreams)
            push!(v, "HEADER-BOTH $(f.rel): both ORIGINAL and UPSTREAM")
        elseif !f.original && isempty(f.upstreams)
            push!(
                v,
                "HEADER-MISSING $(f.rel): needs `# UPSTREAM: …` or `# ORIGINAL: <why>` at the top"
            )
        end
        if f.original
            isempty(f.original_reason) && push!(v, "ORIGINAL-NO-REASON $(f.rel)")
            (startswith(f.rel, "boot/") || occursin(r"^src/pl-", f.rel)) &&
                push!(v, "ORIGINAL-PORT-NAME $(f.rel): that path is reserved for ports")
            isempty(f.markers) ||
                push!(
                    v, "ORIGINAL-HAS-PORT $(f.rel): a ported unit belongs in its port file"
                )
            if swi in available
                for p in shadowed_paths(f.rel)
                    _git_ok(upstream_dirs[swi], "cat-file", "-e", "HEAD:" * p) &&
                        push!(
                            v,
                            "ORIGINAL-SHADOWS-UPSTREAM $(f.rel): swipl-devel has $p — port it or rename"
                        )
                end
            end
            continue
        end
        isempty(f.upstreams) && continue
        f.class in ("code", "design") ||
            push!(v, "CLASS-MISSING $(f.rel): `# CLASS: code` or `design`")
        f.class == "code" && isempty(f.copyright) &&
            push!(
                v,
                "COPYRIGHT-ABSENT $(f.rel): a code port must carry the upstream copyright line(s)"
            )
        for u in f.upstreams
            u.repo in PORT_REPOS || push!(
                v,
                "UNKNOWN-REPO $(f.rel): `$(u.repo)` (known: $(join(PORT_REPOS, ", ")))"
            )
        end
        want = expected_path(f.upstreams[1].repo, f.upstreams[1].path)
        f.rel == want || push!(
            v,
            "PATH-MISMATCH $(f.rel): a port of $(f.upstreams[1].repo) $(f.upstreams[1].path) must live at $want"
        )
        defs = definitions(read(joinpath(root, f.rel), String), f.rel)
        bases = Set(basename(u.path) for u in f.upstreams)
        for (k, m) in enumerate(f.markers)
            m.upstream_base in bases ||
                push!(
                    v,
                    "MARKER-FILE-UNKNOWN $(f.rel):$(m.line): `$(m.upstream_base)` is not one of this file's UPSTREAM files"
                )
            m.diverges && isempty(m.diverges_reason) &&
                push!(v, "DIVERGES-NO-REASON $(f.rel):$(m.line)")
            nxt = findfirst(d -> d[1] > m.line, defs)
            stop = k < length(f.markers) ? f.markers[k + 1].line : typemax(Int)
            if nxt === nothing || defs[nxt][1] > stop
                push!(
                    v,
                    "MARKER-ORPHAN $(f.rel):$(m.line): no definition follows PORT $(m.name)"
                )
            elseif !(defs[nxt][2] == m.jl_name || defs[nxt][2] == m.jl_name * "!")
                push!(
                    v,
                    "DEF-MISMATCH $(f.rel):$(m.line): PORT $(m.name) is followed by `$(defs[nxt][2])`, want `$(m.jl_name)`"
                )
            end
        end
        for u in f.upstreams
            u.repo in available || continue
            dir = upstream_dirs[u.repo]
            if !_git_ok(dir, "cat-file", "-e", u.commit * "^{commit}")
                push!(v, "COMMIT-MISSING $(f.rel): $(u.repo) has no commit $(u.commit)")
                continue
            end
            if !_git_ok(dir, "cat-file", "-e", u.commit * ":" * u.path)
                push!(
                    v,
                    "UPSTREAM-FILE-MISSING $(f.rel): $(u.repo) $(u.path) does not exist at $(u.commit)"
                )
                continue
            end
            text = _git_show(dir, u.commit * ":" * u.path)
            if u === f.upstreams[1]
                sq = _squash(text)
                for c in f.copyright
                    occursin(_squash(c), sq) ||
                        push!(
                            v,
                            "COPYRIGHT-MISMATCH $(f.rel): `$c` is not in $(u.path) @ $(u.commit)"
                        )
                end
            end
            for m in f.markers
                m.upstream_base == basename(u.path) || continue
                _word_in(m.name, text) ||
                    push!(
                        v,
                        "UPSTREAM-NAME-MISSING $(f.rel):$(m.line): `$(m.name)` does not occur in $(u.path) @ $(u.commit)"
                    )
            end
        end
    end
    inv = joinpath(root, inventory)
    if !isfile(inv)
        push!(v, "INVENTORY-MISSING $inventory")
    else
        have = _inventory_section(read(inv, String))
        if have === nothing
            push!(
                v,
                "INVENTORY-MISSING $inventory: no generated section ($INVENTORY_BEGIN … $INVENTORY_END)"
            )
        elseif have != inventory_table(files)
            push!(
                v,
                "INVENTORY-DRIFT $inventory: differs from the headers — run tools/port_check.jl --write-inventory"
            )
        end
        ported = Set(
            m.name for f in files for m in f.markers if m.upstream_base == "pl-vmi.c"
        )
        append!(v, vm_inventory_violations(read(inv, String), ported, inventory))
    end
    # M1: the coverage block (needs every checkout it names), the code graph, the "What is here
    # now" table
    coverage_checked = false
    if isfile(inv)
        invtext = read(inv, String)
        cov = coverage_table(files, upstream_dirs)
        if cov === nothing                  # no checkout: present and non-empty, not recomputed
            sec = _section(invtext, COVERAGE_BEGIN, COVERAGE_END)
            sec === nothing &&
                push!(
                    v,
                    "COVERAGE-MISSING $inventory: no generated section ($COVERAGE_BEGIN … $COVERAGE_END)"
                )
            sec !== nothing && isempty(sec) &&
                push!(v, "COVERAGE-EMPTY $inventory: the generated section is empty")
        else
            coverage_checked = true
            append!(
                v,
                _block_violations(
                    "COVERAGE", inventory, invtext, cov, COVERAGE_BEGIN, COVERAGE_END
                )
            )
        end
    end
    arch = joinpath(root, architecture)
    if !isfile(arch)
        push!(v, "ARCHITECTURE-MISSING $architecture")
    else
        append!(
            v,
            _block_violations(
                "CODE-GRAPH", architecture, read(arch, String), code_graph(root),
                GRAPH_BEGIN,
                GRAPH_END
            )
        )
        append!(v, whats_here_violations(root, files, architecture))
    end
    srcs = [f.rel for f in files if startswith(f.rel, "src/")]
    inv = joinpath(root, inventory)
    isfile(inv) &&
        append!(v, stale_marker_violations(root, srcs, plan_steps(read(inv, String))))
    return (;
        violations=v, files=files, existence_checked=sort!(collect(available)),
        coverage_checked=coverage_checked, markers=marker_counts(root, srcs)
    )
end

# ── markers that name a finished plan step (the divergence audit; user, 2026-10-06) ──────────────
# A `# DIVERGES` or `# NOT PORTED` comment naming a step of the plan (port_inventory's rows: `V5b`,
# `V9`, `R1`, …) WAITS for it — unless it writes the step as history, `since V5b`. A wait on a step
# the inventory marks DONE is stale: what it waited for has come, so the marker needs re-reading.
# The audit found four such in a sample of forty. A step is DONE when its own segment of the plan
# says `✅ DONE` or `✅ REACHED`: a row's first cell for a row step (`V8`), the text after a bold
# sub-step for a sub-step (`**V6b2** — ✅ DONE`). The first occurrence wins, so a later row that
# mentions a step cannot restate it. A row whose sub-steps are not all done (`V5`, with `V5c` open)
# says no DONE of its own. A DECIDED QUESTION counts as done too (user, 2026-10-06): its row in
# port_inventory's decided-questions table says `✅ DECIDED`, so a marker still "waiting for the
# user's Q-B" is stale. It waits for the step that implements the decision, and cites the decision
# as history, `since Q-B`.
const RX_PLAN_ROW = r"^\| \*\*([A-Z]\d+[a-z]?\d*|Q-[A-Z]+\d*)\*\*"
const RX_SUBSTEP_BOLD = r"\*\*([A-Z]\d+[a-z]\d*)\*\*"
const RX_ANY_STEP_BOLD = r"\*\*[A-Z]\d+[a-z]?\d*\*\*"
const RX_STEP_DONE = r"✅\s*\**(?:DONE|REACHED|DECIDED)"
# a marker's start — not a backticked mention of one in prose
const RX_MARKER_START = r"(?<!`)#\s*(?:DIVERGES|NOT PORTED)\b"
# a step named in a marker, unless written as history (`since V5b`)
const RX_STEP_WAIT = r"(?<![Ss]ince )\b([A-Z]\d+[a-z]?\d*|Q-[A-Z]+\d*)\b"

"The plan's steps and whether each is DONE, from port_inventory's plan rows (see above)."
function plan_steps(inventory_text::AbstractString)::Dict{String, Bool}
    status = Dict{String, Bool}()
    for row in eachline(IOBuffer(inventory_text))
        m = match(RX_PLAN_ROW, row)
        m === nothing && continue
        cells = split(row, '|')
        haskey(status, m[1]) || (status[m[1]] = occursin(RX_STEP_DONE, cells[2]))
        for b in eachmatch(RX_SUBSTEP_BOLD, row)
            haskey(status, b[1]) && continue
            seg = SubString(row, b.offset + ncodeunits(b.match))
            nxt = match(RX_ANY_STEP_BOLD, seg)
            nxt === nothing || (seg = SubString(seg, 1, prevind(seg, nxt.offset)))
            status[b[1]] = occursin(RX_STEP_DONE, first(seg, 200))
        end
    end
    return status
end

"""
    marker_blocks(text) -> [(line, block)]

The `# DIVERGES` and `# NOT PORTED` markers of a source file: each with its comment block — the
following comment lines, up to the next `# PORT:` — or, for a marker at the end of a code line, that
comment alone.
"""
function marker_blocks(text::AbstractString)::Vector{Tuple{Int, String}}
    lines = split(text, '\n')
    out = Tuple{Int, String}[]
    i = 1
    while i <= length(lines)
        m = match(RX_MARKER_START, lines[i])
        if m === nothing
            i += 1
            continue
        end
        if startswith(lstrip(lines[i]), "#")
            j = i
            while j < length(lines) && startswith(lstrip(lines[j + 1]), "#") &&
                  !occursin(RX_PORT_ANY, lstrip(lines[j + 1]))
                j += 1
            end
            push!(out, (i, join(lines[i:j], "\n")))
            i = j + 1
        else
            push!(out, (i, SubString(lines[i], m.offset)))
            i += 1
        end
    end
    return out
end

"""
    stale_marker_violations(root, rels, steps) -> violations

`MARKER-STALE` for each step a marker in the source files `rels` waits for — names, not as
`since …` — that `steps` marks DONE (a plan step) or DECIDED (a question).
"""
function stale_marker_violations(
    root::AbstractString, rels::Vector{String}, steps::Dict{String, Bool}
)::Vector{String}
    done = Set(k for (k, d) in steps if d)
    v = String[]
    for rel in rels
        for (line, block) in marker_blocks(read(joinpath(root, rel), String))
            for tok in unique(m[1] for m in eachmatch(RX_STEP_WAIT, block))
                tok in done || continue
                fix = if startswith(tok, "Q-")
                    "DECIDED — re-read the marker; it waits for the step that implements the decision and cites it as `since $tok`"
                else
                    "DONE — re-read the marker; a step it no longer waits for is written `since $tok`"
                end
                push!(
                    v,
                    "MARKER-STALE $rel:$line: names $tok, which docs/port_inventory.md marks $fix"
                )
            end
        end
    end
    return v
end

"""
    marker_counts(root, rels) -> (; diverges, not_ported, both)

How the markers of the source files `rels` split (user, 2026-10-06): lines that are `# DIVERGES`
markers (a difference from upstream), lines that are `# NOT PORTED` markers (an absence), and the
`# DIVERGES` lines that also say `NOT PORTED`, which are still to be split as their files are
touched.
"""
function marker_counts(root::AbstractString, rels::Vector{String})
    d = n = both = 0
    for rel in rels, l in eachline(joinpath(root, rel))
        isd = occursin(r"(?<!`)#\s*DIVERGES\b", l)
        d += isd
        n += occursin(r"(?<!`)#\s*NOT PORTED\b", l)
        both += isd && occursin("NOT PORTED", l)
    end
    return (; diverges=d, not_ported=n, both=both)
end

"Replace the content between `b` and `e` in the file `path` with `gen`."
function _write_section(path::AbstractString, b::AbstractString, e::AbstractString, gen)
    text = read(path, String)
    i = findfirst(b, text)
    j = findfirst(e, text)
    (i === nothing || j === nothing || last(i) > first(j)) &&
        error("no generated section ($b … $e) in $path")
    write(path, text[1:last(i)] * "\n" * gen * "\n" * text[first(j):end])
    return nothing
end

"""
Rewrite the generated sections from the sources: the inventory table and the coverage block
(docs/port_inventory.md — coverage needs every upstream checkout) and the code graph
(docs/architecture.md).
"""
function write_inventory(
    pkgroot::AbstractString;
    inventory::AbstractString="docs/port_inventory.md",
    architecture::AbstractString="docs/architecture.md",
    upstream_dirs::Dict{String, String}=default_upstream_dirs()
)
    root = abspath(pkgroot)
    files = port_check(root; upstream_dirs=upstream_dirs).files
    inv = joinpath(root, inventory)
    _write_section(inv, INVENTORY_BEGIN, INVENTORY_END, inventory_table(files))
    cov = coverage_table(files, upstream_dirs)
    cov === nothing &&
        error("the coverage block needs every upstream checkout the headers name")
    _write_section(inv, COVERAGE_BEGIN, COVERAGE_END, cov)
    _write_section(joinpath(root, architecture), GRAPH_BEGIN, GRAPH_END, code_graph(root))
    return inv
end

if abspath(PROGRAM_FILE) == @__FILE__
    root = joinpath(@__DIR__, "..")
    if "--write-inventory" in ARGS
        println("wrote ", write_inventory(root))
    end
    r = port_check(root)
    println("port_check: $(length(r.files)) file(s), upstream checked for: ",
        if isempty(r.existence_checked)
            "NONE (no checkout found)"
        else
            join(r.existence_checked, ", ")
        end)
    foreach(x -> println("  ", x), r.violations)
    exit(isempty(r.violations) && !isempty(r.files) ? 0 : 1)
end
